package org.apache.jsp.specifiques.calendrierEquipement;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import fr.osys.quartis.multilanguage.manager.WebRessources;
import fr.osys.quartis.multilanguage.manager.MultiLanguageManager;
import java.util.HashMap;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.List;
import java.util.ArrayList;
import commun.beans.Atelier;
import commun.beans.SecteurGeo;
import commun.beans.HoraireEquipement;
import commun.resources.Constants;

public final class calendrierEquipementMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");

    HttpSession idSess = request.getSession();
//idSess.setAttribute("idLocale", new Locale("en"));
//idSess.setAttribute("codeSite", "LAV");
    Locale idLoca = (Locale) idSess.getAttribute("idLocale");

//idLoca = new Locale("fr");
//idLoca = new Locale("de");
//idLoca = Locale.GERMAN;
    String baseNameForBundle = "/specifiques/calendrier/resources/language";
    ResourceBundle rb = ResourceBundle.getBundle(baseNameForBundle, idLoca);
    //Si RessourceBundle ne trouve pas la langue de idLoca, il renvoi la langue par defaut de la JVM installee : on force l anglais par defaut
    if (!idLoca.getLanguage().equals(rb.getLocale().getLanguage())) {
        //rb = ResourceBundle.getBundle(baseNameForBundle, Locale.ENGLISH);
        rb = ResourceBundle.getBundle(baseNameForBundle, Constants.DEFAULT_LOCALE);
    }

    List listSecteur = (List) idSess.getAttribute("listSecteur");
    List listAtelier = (List) idSess.getAttribute("listAtelier");
    String dateJour = (String) idSess.getAttribute("date");
    List listHoraire = (List) idSess.getAttribute("listHoraire");
    String codeSite = (String) idSess.getAttribute("codeSite");
    String deltaUTC = (String) idSess.getAttribute("deltaUTC");

//codeSite = "LAV";
    WebRessources webRessources = new WebRessources(request.getServerName(), String.valueOf(request.getServerPort()));
    //WebRessources webRessources = new WebRessources("4122B", "8383");
    //WebRessources webRessources = new WebRessources("2991B", "8384");
    MultiLanguageManager.INSTANCE.setSite(codeSite);
    MultiLanguageManager.INSTANCE.setLocale(idLoca);
    MultiLanguageManager.INSTANCE.setWebRessources(webRessources);

    //--> Recuperation des designations du contexte ATELIER_DESI_ATEL
    HashMap<String, String> hashMapValueAtelier = MultiLanguageManager.INSTANCE.getContextValueLanguage("ATELIER_DESI_ATEL");

    //--> Recuperation des designations du contexte SECTION_GEO_DESI_SECT_GEOG
    HashMap<String, String> hashMapValueSectionGeo = MultiLanguageManager.INSTANCE.getContextValueLanguage("SECTION_GEO_DESI_SECT_GEOG");

    //--> Recuperation des designations du contexte HORAIRE_MACHINE_DESI_HORA
    HashMap<String, String> hashMapValueHoraireMach = MultiLanguageManager.INSTANCE.getContextValueLanguage("HORAIRE_MACHINE_DESI_HORA");


      out.write("\n");
      out.write("\n");
      out.write("<html xml:lang=\"fr\" lang=\"fr\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("        <title>OPTIMA WEB (c)OSYS 2010</title>\n");
      out.write("\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("\n");
      out.write("        <!-- Mémorisation du ContextPath pour les Javascript et URL AJAX en particulier -->\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            var contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <!-- Initialisation de la méthode AJAX -->\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/ajax/ajax-init.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Fonction de controles des dates -->\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/fonctions/calendrierFonctions.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/graphiques/windowAdjustment.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Objet Calendrier -->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"");
      out.print(request.getContextPath());
      out.write("/javascript/calendrier/css/calendar.css\"/>\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/calendrier/calendar.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/calendrier/calendar-setup.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/calendrier/lang/calendar-en.js\"></script> <!-- Charger le calendrier anglais en 1er (celui par defaut) -->\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/calendrier/lang/calendar-");
      out.print((MultiLanguageManager.INSTANCE.getLocale()).toLowerCase());
      out.write(".js\"></script> <!-- Charger le calendrier de la langue si inexistant il n est pas charge et on a celui par defaut) -->\n");
      out.write("\n");
      out.write("        <!-- Gestion du Menu Contextuel -->\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/javascript/menuContextuel/menuContextuel.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"");
      out.print(request.getContextPath());
      out.write("/javascript/menuContextuel/css/style.css\"/>\n");
      out.write("\n");
      out.write("        <!-- Gestion des données  -->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"");
      out.print(request.getContextPath());
      out.write("/specifiques/calendrierEquipement/css/style.css\"/>\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/specifiques/calendrierEquipement/javascript/calendrierEquipementMain.js\"></script>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body onload=\"callCalendrierEquipement();\" \n");
      out.write("          dir=\"#LANG_DIR\" \n");
      out.write("          style=\"-moz-user-select:none;\">\n");
      out.write("\n");
      out.write("        <input type=\"hidden\" id=\"codeSite\" value=\"");
      out.print(codeSite);
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"deltaUTC\" value=\"");
      out.print(deltaUTC);
      out.write("\" />\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"cachForm\" class=\"cachForm\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"addForm\" class=\"inputForm\">\n");
      out.write("            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"98%\" align=\"center\">\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"inputFormTitle\" colspan=\"2\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AJOUT_HORAIRE_L"));
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"100%\" colspan=\"2\">\n");
      out.write("                        <table border=\"0\" style=\"border: 1px solid #878282;\" cellpadding=\"0\" cellspacing=\"2px\" width=\"100%\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\" width=\"30%\">");
      out.print(rb.getString("O_STANDARD_PARAM_HORAIRE_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                                <td>\n");
      out.write("                                    <select name=\"listeAjoutHoraire\" id=\"idListeAjoutHoraire\" style=\"width: 250px;\" size=\"1\">\n");
      out.write("                                        <option value=\"-\" selected=\"true\">---</option>\n");
      out.write("                                        ");

                                            HoraireEquipement h = new HoraireEquipement();
                                            for (int i = 0; i < listHoraire.size(); i++) {
                                                h = (HoraireEquipement) listHoraire.get(i);
                                        
      out.write("\n");
      out.write("                                        <option value='");
      out.print(h.getCodeHora());
      out.write("'>\n");
      out.write("                                            <!--=h.getCodeHora() + \" - \" + h.getDesiHora()-->\n");
      out.write("                                            <!--=h.getCodeHora() + \" - \" + hashMapValueHoraireMach.get(h.getDesiHora())!=null?hashMapValueAtelier.get(h.getDesiHora()):h.getDesiHora()-->\n");
      out.write("                                            ");
      out.print(h.getCodeHoraSite() + " - " + (((hashMapValueHoraireMach.get(h.getDesiHora()) != null) && (hashMapValueHoraireMach.get(h.getDesiHora()) != "null")) ? hashMapValueHoraireMach.get(h.getDesiHora()) : h.getDesiHora()));
      out.write("\n");
      out.write("                                        </option>\n");
      out.write("                                        ");
}
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\"><input name=\"idMachAjout\" id=\"idMachAjout1\" value=\"1\" type=\"radio\" checked=\"checked\"/></td>\n");
      out.write("                                <td class=\"commentText\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_PARAM_EQUIPEMENT_SELECTIONNE_LL"));
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\"><input name=\"idMachAjout\" id=\"idMachAjout2\" value=\"2\" type=\"radio\"/></td>\n");
      out.write("                                <td class=\"commentText\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_PARAM_EQUIPEMENT_TOUS_LL"));
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"2\">\n");
      out.write("                                    <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse\">\n");
      out.write("                                        <tr>\n");
      out.write("                                            <td class=\"inputText\" width=\"30%\">");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_DU_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                                            <td><input type=\"text\" id=\"idDateDebutAjout\"  readonly=\"readonly\" size=\"9\"/></td>\n");
      out.write("                                            <td><img src=\"specifiques/calendrierEquipement/images/cal.jpeg\" alt=\"+\" id=\"btnDateDebutAjout\" style=\"cursor: pointer;\" title=\"\"/></td>\n");
      out.write("                                            <td class=\"inputText\" width=\"30%\">");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_AU_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                                            <td><input type=\"text\" id=\"idDateFinAjout\"  readonly=\"readonly\" size=\"9\"/></td>\n");
      out.write("                                            <td><img src=\"specifiques/calendrierEquipement/images/cal.jpeg\" alt=\"+\" id=\"btnDateFinAjout\" style=\"cursor: pointer;\" title=\"\"/></td>\n");
      out.write("                                        </tr>\n");
      out.write("                                    </table>\n");
      out.write("                                    <script type=\"text/javascript\">\n");
      out.write("                                        Calendar.setup({\n");
      out.write("                                            inputField: \"idDateDebutAjout\", // id of the input field\n");
      out.write("                                            ifFormat: \"%d/%m/%Y\", // format of the input field\n");
      out.write("                                            showsTime: false, // will display a time selector\n");
      out.write("                                            timeFormat: \"24\",\n");
      out.write("                                            button: \"btnDateDebutAjout\", // trigger for the calendar (button ID)\n");
      out.write("                                            singleClick: true, // double-click mode\n");
      out.write("                                            step: 1                // show all years in drop-down boxes (instead of every other year as default)\n");
      out.write("                                        });\n");
      out.write("                                        Calendar.setup({\n");
      out.write("                                            inputField: \"idDateFinAjout\", // id of the input field\n");
      out.write("                                            ifFormat: \"%d/%m/%Y\", // format of the input field\n");
      out.write("                                            showsTime: false, // will display a time selector\n");
      out.write("                                            timeFormat: \"24\",\n");
      out.write("                                            button: \"btnDateFinAjout\", // trigger for the calendar (button ID)\n");
      out.write("                                            singleClick: true, // double-click mode\n");
      out.write("                                            step: 1                // show all years in drop-down boxes (instead of every other year as default)\n");
      out.write("                                        });\n");
      out.write("                                    </script>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"50%\" align=\"center\" height=\"40px\">\n");
      out.write("                        <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_ENREGISTRER_L"));
      out.write("\" type=\"button\" onClick =\"callCalendrierEquipementAdd();\n");
      out.write("                                document.getElementById('idListeAjoutHoraire').style.visibility = 'hidden';\" />\n");
      out.write("                    </td>\n");
      out.write("                    <td width=\"50%\" align=\"center\">\n");
      out.write("                        <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_ANNULER_L"));
      out.write("\" type=\"button\" onClick = \"closeForm('addForm');\n");
      out.write("                                document.getElementById('idListeAjoutHoraire').style.visibility = 'hidden';\" />\n");
      out.write("                    </td>\n");
      out.write("                </tr>  \n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"deleteForm\" class=\"inputForm\">\n");
      out.write("            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"98%\" align=\"center\">\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"inputFormTitle\" colspan=\"2\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_SUPPRESSION_HORAIRE_L"));
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"100%\" colspan=\"2\">\n");
      out.write("                        <table border=\"0\" style=\"border: 1px solid #878282;\" cellpadding=\"0\" cellspacing=\"2px\" width=\"100%\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\" width=\"30%\"><input name=\"idMachDelete\" id=\"idMachDelete1\" value=\"1\" type=\"radio\" checked=\"checked\"></td>\n");
      out.write("                                <td class=\"commentText\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_PARAM_PLAGE_SELECTIONNE_LL"));
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\"><input name=\"idMachDelete\" id=\"idMachDelete2\" value=\"2\" type=\"radio\"></td>\n");
      out.write("                                <td class=\"commentText\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_PARAM_PLAGE_COMPLETE_LL"));
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"50%\" align=\"center\" height=\"40px\">\n");
      out.write("                        <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_ENREGISTRER_L"));
      out.write("\" type=\"button\" onClick =\"callCalendrierEquipementDelete();\" />\n");
      out.write("                    </td>\n");
      out.write("                    <td width=\"50%\" align=\"center\">\n");
      out.write("                        <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_ANNULER_L"));
      out.write("\" type=\"button\" onClick = \"closeForm('deleteForm');\" />\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"calcForm\" class=\"inputForm\">\n");
      out.write("            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"98%\" align=\"center\">\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"inputFormTitle\" colspan=\"2\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_CALCUL_OUVERTURE_L"));
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"100%\" colspan=\"2\">\n");
      out.write("                        <table border=\"0\" style=\"border: 1px solid #878282;\" cellpadding=\"0\" cellspacing=\"2px\" width=\"100%\">\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\" width=\"30%\"><input name=\"idMachCalcul\" id=\"idMachCalcul1\" value=\"1\" type=\"radio\" checked=\"checked\"/></td>\n");
      out.write("                                <td class=\"commentText\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_PARAM_EQUIPEMENT_SELECTIONNE_LL"));
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"inputText\"><input name=\"idMachCalcul\" id=\"idMachCalcul2\" value=\"2\" type=\"radio\"/></td>\n");
      out.write("                                <td class=\"commentText\">");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_PARAM_EQUIPEMENT_TOUS_LL"));
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"2\">\n");
      out.write("                                    <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse\">\n");
      out.write("                                        <tr>\n");
      out.write("                                            <td class=\"inputText\" width=\"30%\">");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_DU_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                                            <td><input type=\"text\" id=\"idDateDebutCalcul\"  readonly=\"readonly\" size=\"9\"/></td>\n");
      out.write("                                            <td><img src=\"specifiques/calendrierEquipement/images/cal.jpeg\" alt=\"+\" id=\"btnDateDebutCalcul\" style=\"cursor: pointer;\" title=\"\"/></td>\n");
      out.write("                                            <td class=\"inputText\" width=\"30%\">");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_AU_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                                            <td><input type=\"text\" id=\"idDateFinCalcul\"  readonly=\"readonly\" size=\"9\"/></td>\n");
      out.write("                                            <td><img src=\"specifiques/calendrierEquipement/images/cal.jpeg\" alt=\"+\" id=\"btnDateFinCalcul\" style=\"cursor: pointer;\" title=\"\"/></td>\n");
      out.write("                                        </tr>\n");
      out.write("                                    </table>\n");
      out.write("                                    <script type=\"text/javascript\">\n");
      out.write("                                        Calendar.setup({\n");
      out.write("                                            inputField: \"idDateDebutCalcul\", // id of the input field\n");
      out.write("                                            ifFormat: \"%d/%m/%Y\", // format of the input field\n");
      out.write("                                            showsTime: false, // will display a time selector\n");
      out.write("                                            timeFormat: \"24\",\n");
      out.write("                                            button: \"btnDateDebutCalcul\", // trigger for the calendar (button ID)\n");
      out.write("                                            singleClick: true, // double-click mode\n");
      out.write("                                            step: 1                // show all years in drop-down boxes (instead of every other year as default)\n");
      out.write("                                        });\n");
      out.write("                                        Calendar.setup({\n");
      out.write("                                            inputField: \"idDateFinCalcul\", // id of the input field\n");
      out.write("                                            ifFormat: \"%d/%m/%Y\", // format of the input field\n");
      out.write("                                            showsTime: false, // will display a time selector\n");
      out.write("                                            timeFormat: \"24\",\n");
      out.write("                                            button: \"btnDateFinCalcul\", // trigger for the calendar (button ID)\n");
      out.write("                                            singleClick: true, // double-click mode\n");
      out.write("                                            step: 1                // show all years in drop-down boxes (instead of every other year as default)\n");
      out.write("                                        });\n");
      out.write("                                    </script>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                        </table>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td width=\"50%\" align=\"center\" height=\"40px\">\n");
      out.write("                        <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_ENREGISTRER_L"));
      out.write("\" type=\"button\" onClick =\"callCalendrierEquipementCalcul();\" />\n");
      out.write("                    </td>\n");
      out.write("                    <td width=\"50%\" align=\"center\">\n");
      out.write("                        <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_ANNULER_L"));
      out.write("\" type=\"button\" onClick = \"closeForm('calcForm');\" />\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"dataOnLoad\" class=\"popUp\">\n");
      out.write("            <br>");
      out.print(rb.getString("O_STANDARD_MSG_CHARGEMENT_DONNEES_LL"));
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"calcProcess\" class=\"popUp\">\n");
      out.write("            <br><div id=\"p1\">");
      out.print(rb.getString("O_STANDARD_MSG_CALCUL_DONNEES_LL"));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"ie5menu\" class=\"menuclickdroit\" onmouseover=\"highlightie5(event, '#3872A8', '#FFFFFF');\" onmouseout=\"lowlightie5(event, '', '#000000');\" onclick=\"jumptoie5(event);\" style=\"display:block; visibility:hidden;\">\n");
      out.write("            <div class=\"menuitems\" onclick=\"openAddForm();\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AJOUT_HORAIRE_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AJOUT_HORAIRE_L"));
      out.write("</div>\n");
      out.write("            <div class=\"menuitems\" onclick=\"openDeleteForm();\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_SUPPRESSION_HORAIRE_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_SUPPRESSION_HORAIRE_L"));
      out.write("</div>\n");
      out.write("            <hr/>\n");
      out.write("            <div class=\"menuitems\" onclick=\"openCalcForm();\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_CALCUL_OUVERTURE_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_CALCUL_OUVERTURE_L"));
      out.write("</div>\n");
      out.write("            <hr/>\n");
      out.write("            <div class=\"menuitems\" onclick=\"selectDisplayMode(1);\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_HORAIRE_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_HORAIRE_L"));
      out.write("</div>\n");
      out.write("            <div class=\"menuitems\" onclick=\"selectDisplayMode(2);\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_OUVERTURE_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_OUVERTURE_L"));
      out.write("</div>\n");
      out.write("            <div class=\"menuitems\" onclick=\"selectDisplayMode(3);\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_CALCULE_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_CALCULE_L"));
      out.write("</div>\n");
      out.write("            <hr/>\n");
      out.write("            <div class=\"menuitems\" onclick=\"selectDisplayDefault();\" title='");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_DEFAUT_LL"));
      out.write('\'');
      out.write('>');
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MENU_AFFICHE_DEFAUT_L"));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            //--> Gestion du menu contextuel\n");
      out.write("            menuobj = document.getElementById(\"ie5menu\");\n");
      out.write("            MCenable = true;\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <script type=\"Text/JavaScript\">\n");
      out.write("            window.onresize=function() {\n");
      out.write("            centerObject(\"dataOnLoad\");\n");
      out.write("            centerObject(\"calcProcess\");\n");
      out.write("            centerObject(\"addForm\");\n");
      out.write("            centerObject(\"deleteForm\");\n");
      out.write("            centerObject(\"calcForm\");\n");
      out.write("            }\n");
      out.write("            centerObject(\"dataOnLoad\");\n");
      out.write("            centerObject(\"calcProcess\");\n");
      out.write("            centerObject(\"addForm\");\n");
      out.write("            centerObject(\"deleteForm\");\n");
      out.write("            centerObject(\"calcForm\");\n");
      out.write("            setObjectOpacity(\"cachForm\",50);\n");
      out.write("            document.body.oncontextmenu = function(){return false;}\n");
      out.write("            document.body.ondragstart = function(){return false;}\n");
      out.write("            document.body.onselectstart = function(){return false;}\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <input type=\"hidden\" id=\"calRes_msg_1\" value=\"");
      out.print(rb.getString("O_STANDARD_MSG_DATE_NON_SAISIE_LL"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResWeek\"  value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_SEMAINES_LL"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_1\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_LUNDI_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_2\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_MARDI_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_3\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_MERCREDI_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_4\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_JEUDI_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_5\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_VENDREDI_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_6\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_SAMEDI_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calResDay_7\" value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_DIMANCHE_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"caldeta_2\"   value=\"");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_DU_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"caldeta_3\"   value=\"");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_AU_L"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"caldeta_4\"   value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_TEMPS_OUVERTURE_LL"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"caldeta_5\"   value=\"");
      out.print(rb.getString("O_STANDARD_LABEL_DISPONIBILITE_OPERATIONNELLE_LL"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"calRes_msg_4\" value=\"");
      out.print(rb.getString("O_CALENDRIER_EQUIPEMENT_MSG_DATE_ATTRIBUEE_LL"));
      out.write("\" />\n");
      out.write("        <input type=\"hidden\" id=\"sip_msg_date\" value=\"");
      out.print(rb.getString("O_STANDARD_MSG_DATE_ERREUR_FORMAT_LL"));
      out.write("\" />\n");
      out.write("        <INPUT type=\"hidden\" id=\"idModeAffichage\" value=\"1\"/>\n");
      out.write("        <INPUT type=\"hidden\" id=\"idDefautAffichage\" value=\"1\"/>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <table style=\"width:100%;\" id=\"criteria\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("            <tr>\n");
      out.write("                <td class=\"inputText\">");
      out.print(rb.getString("O_STANDARD_PARAM_DATE_CALENDRIER_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                <td>\n");
      out.write("                    <table cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse: collapse\"><tr>\n");
      out.write("                            <td><input type=\"text\" name=\"dateCaleRes\" id=\"idDateCaleRes\" value='");
      out.print(dateJour);
      out.write("' size=\"10\"/></td>\n");
      out.write("                            <td><img src=\"specifiques/calendrierEquipement/images/cal.jpeg\" alt=\"+\" id=\"btnDateCaleRes\" style=\"cursor: pointer;\" title=\"\"/></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                    <div id=\"calendarDisplay\" style=\"position:absolute; visibility:hidden;\"></div>\n");
      out.write("                    <script type=\"text/javascript\">\n");
      out.write("                        Calendar.setup({\n");
      out.write("                            inputField: \"idDateCaleRes\", // id of the input field\n");
      out.write("                            displayArea: \"calendarDisplay\",\n");
      out.write("                            ifFormat: \"%d/%m/%Y\", // format of the input field\n");
      out.write("                            showsTime: false, // will display a time selector\n");
      out.write("                            timeFormat: \"24\",\n");
      out.write("                            button: \"btnDateCaleRes\", // trigger for the calendar (button ID)\n");
      out.write("                            singleClick: true, // double-click mode\n");
      out.write("                            step: 1                // show all years in drop-down boxes (instead of every other year as default)\n");
      out.write("                        });\n");
      out.write("                    </script>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"inputText\">");
      out.print(rb.getString("O_STANDARD_PARAM_ATELIER_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                <td>\n");
      out.write("                    <select name=\"listeAtelCaleRes\" id=\"idListeAtelCaleRes\" style=\"width: 200px;\" size=\"1\" >\n");
      out.write("                        <option value=\"-\" selected=\"true\">---</option>\n");
      out.write("                        ");

                            Atelier atel = new Atelier();
                            for (int i = 0; i < listAtelier.size(); i++) {
                                atel = (Atelier) listAtelier.get(i);
                        
      out.write("<option value='");
      out.print(atel.getCodeAtel());
      out.write("'  title='");
      out.print(atel.getDesiAtel());
      out.write("'>\n");
      out.write("                            <!--\n");
      out.write("                            /*=atel.getCodeAtel() + \" - \" + atel.getDesiAtel()*/-->\n");
      out.write("                            <!--=atel.getCodeAtel() + \" - \" + atel.getDesiAtel(idLoca.getLanguage())-->\n");
      out.write("                            <!--=atel.getCodeAtel() + \" - \" + hashMapValueAtelier.get(atel.getDesiAtel())!=null?hashMapValueAtelier.get(atel.getDesiAtel()):atel.getDesiAtel()-->\n");
      out.write("                            ");
      out.print(atel.getCodeAtelSite() + " - " + (((hashMapValueAtelier.get(atel.getDesiAtel()) != null) && (hashMapValueAtelier.get(atel.getDesiAtel()) != "null")) ? hashMapValueAtelier.get(atel.getDesiAtel()) : atel.getDesiAtel()));
      out.write("\n");
      out.write("                        </option>\n");
      out.write("\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("                <td align=\"right\" rowspan=\"2\">\n");
      out.write("                    <input style=\"cursor:pointer; width: 90px; height: 26px;\" value=\"");
      out.print(rb.getString("O_STANDARD_BOUTON_RECHERCHE_L"));
      out.write("\" name=\"recherche\" type=\"button\" onClick=\"callCalendrierEquipement('init');\"/>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td style=\"text-align: right; font-family: tahoma; font-weight: bold; font-size : 12px; color: rgb(51,51,51);\">");
      out.print(rb.getString("O_STANDARD_PARAM_NOMBRE_SEMAINES_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                <td style=\"text-align: left;\">\n");
      out.write("                    <select name=\"nbSemaineCaleRes\" id=\"idNbSemaineCaleRes\" style=\"width: 35px;\" size=\"1\" onclick=\"callCalendrierEquipement('init');\">\n");
      out.write("                        <option value=\"1\">1</option>\n");
      out.write("                        <option value=\"2\">2</option>\n");
      out.write("                        <option value=\"3\" selected=\"true\">3</option>\n");
      out.write("                        <option value=\"4\">4</option>\n");
      out.write("                        <option value=\"5\">5</option>\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("                <td style=\"text-align: right; font-family: tahoma; font-weight: bold; font-size : 12px; color: rgb(51,51,51);\">");
      out.print(rb.getString("O_STANDARD_PARAM_SECTEUR_GEOGRAPHIQUE_L"));
      out.write("&nbsp;:&nbsp;</td>\n");
      out.write("                <td style=\"text-align: left;\">\n");
      out.write("                    <select name=\"listeSecteurCaleRes\" id=\"idListeSecteurCaleRes\" style=\"width: 200px;\" size=\"1\" >\n");
      out.write("                        <option value=\"-\" selected=\"true\">---</option>\n");
      out.write("                        ");

                            SecteurGeo sg = new SecteurGeo();
                            for (int i = 0; i < listSecteur.size(); i++) {
                                sg = (SecteurGeo) listSecteur.get(i);
                        
      out.write("<option value='");
      out.print(sg.getCodeSecteur());
      out.write("'  title='");
      out.print(sg.getDesiSecteur());
      out.write("'>\n");
      out.write("                            <!--=sg.getCodeSecteur() + \" - \" + sg.getDesiSecteur()-->\n");
      out.write("                            <!--=sg.getCodeSecteur() + \" - \" + hashMapValueSectionGeo.get(sg.getDesiSecteur())!=null?hashMapValueSectionGeo.get(sg.getDesiSecteur()):sg.getDesiSecteur()-->\n");
      out.write("                            ");
      out.print(sg.getCodeSecteurSite() + " - " + (((hashMapValueSectionGeo.get(sg.getDesiSecteur()) != null) && (hashMapValueSectionGeo.get(sg.getDesiSecteur()) != "null")) ? hashMapValueSectionGeo.get(sg.getDesiSecteur()) : sg.getDesiSecteur()));
      out.write("\n");
      out.write("\n");
      out.write("                        </option>\n");
      out.write("\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <table border=\"0\" style=\"width:98%;\">\n");
      out.write("            <tr>\n");
      out.write("                <td style=\"width:210px;text-align:center;\"></td>\n");
      out.write("                <td>\n");
      out.write("                    <table border=\"0\" style=\"width:100%;\">\n");
      out.write("                        <tr>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_left_double.jpeg\" alt=\"Week--\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('doubledown');\"/></td>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_left.jpeg\" alt=\"Week-\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('down');\"/></td>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_right.jpeg\" alt=\"Week+\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('up');\"/></td>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_right_double.jpeg\" alt=\"Week++\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('doubleup');\"/></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        <div id=\"idCalDiv\" style=\"width:98%; border: 0px solid #878282; z-index: 0;\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <table border=\"0\" style=\"width:98%;\">\n");
      out.write("            <tr>\n");
      out.write("                <td style=\"width:210px;text-align:center;\"></td>\n");
      out.write("                <td>\n");
      out.write("                    <table border=\"0\" style=\"width:100%;\">\n");
      out.write("                        <tr>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_left_double.jpeg\" alt=\"Week--\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('doubledown');\"/></td>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_left.jpeg\" alt=\"Week-\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('down');\"/></td>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_right.jpeg\" alt=\"Week+\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('up');\"/></td>\n");
      out.write("                            <td style=\"width:25%;text-align:center;\"><img src=\"specifiques/calendrierEquipement/images/arrow_right_double.jpeg\" alt=\"week++\" style=\"cursor:pointer;\" onclick=\"removePreviousZone();\n");
      out.write("                                    callCalendrierEquipement('doubleup');\"/></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
