new f_class("f_columnSortDialog",{extend:f_dialog,members:{f_columnSortDialog:function(r,n){var t=f_shell,e=this
e.f_super(arguments,n?n:t.PRIMARY_MODAL_STYLE|t.TITLE_STYLE|t.CLOSE_STYLE|t.COPY_STYLESHEET)
e._1f=r
e._ss=f_columnSortConfigurator.f_newInstance(e,r)
e.Ee()},Ee:function(){this.f_setTitle(f_resourceBundle.Get(f_columnSortDialog).f_get("TITLE"))},f_finalize:function(){var n,e=this,t
e._1f=n
if(t=e._ss){e._ss=n
f_classLoader.Destroy(t)}e.f_super(arguments)},fl:function(){return f_columnSortDialog.w},f_fillBody:function(en){var fn=f_columnSortDialog,C=f_resourceBundle,l=f_core,k="px",U="input",ot="li",j="f_columnSortDialog_button",ri="button",g="td",rr="tr",r,W,t,m,o,i,f,c,u,b,p,tt,E,h,a,n,e,v,T,z,s,d,A,G,R
r=this
r.f_super(arguments,en)
W="f_columnSortDialog"
t=en.ownerDocument
m=r._1f
o=t.createElement("form")
o.className="f_columnSortDialog_form"
o.style.width=r.f_getWidth()+k
o.style.height=r.f_getHeight()+k
en.appendChild(o)
i=t.createElement("ul")
o.appendChild(i)
i.className="f_columnSortDialog_dialog"
i.style.width=r.f_getWidth()+k
i.style.height=r.f_getHeight()+k
i.width=r.f_getWidth()
f=l.B(i,ot,{className:W+"_corps_tr"})
c=t.createElement("table")
f.appendChild(c)
c.cellPadding=c.cellSpacing=0
c.width="100%"
u=t.createElement("tbody")
c.appendChild(u)
b=[]
p=[]
tt=m.f_getSortedColumns()
E=f_columnSortConfigurator.GetColumns(m)
h=E.length
if(h>3)h=3
for(a=0;a<h;a++){n=t.createElement(rr)
u.appendChild(n)
e=t.createElement(g)
n.appendChild(e)
e.width=20
e=t.createElement(g)
n.appendChild(e)
e.colSpan=2
v=t.createElement("label")
e.appendChild(v)
v.className="f_columnSortDialog_text"
T=a==0?"SORT_BY":"NEXT_SORT_BY"
z=C.Get(fn).f_get(T)
l.nr(v,z)
n=t.createElement(rr)
u.appendChild(n)
e=t.createElement(g)
n.appendChild(e)
e.width=20
e=t.createElement(g)
n.appendChild(e)
e.width=120
s=t.createElement("select")
e.appendChild(s)
s.className="f_columnSortDialog_select"
p.push(s)
e=t.createElement(g)
n.appendChild(e)
r._Cy(e,"sort"+a,s,b)
if(a+1<h){n=t.createElement(rr)
u.appendChild(n)
n.style.height="20px"
n.className="f_columnSortDialog_hr"
e=t.createElement(g)
n.appendChild(e)
e.colSpan=3
d=t.createElement("div")
e.appendChild(d)
l.nr(d," ")}}f=l.B(i,ot,{className:"f_shellDecorator_body_buttons"})
A=l.B(f,U,{type:"submit",className:j,value:C.Get(f_shell).f_get("VALID_BUTTON")})
if(r._nr&fn.APPLY_BUTTON)G=l.B(f,U,{type:ri,className:j,value:C.Get(f_shell).f_get("APPLY_BUTTON")})
R=l.B(f,U,{type:ri,className:j,value:C.Get(f_shell).f_get("CANCEL_BUTTON")})
r._ss.f_fillBody(p,b,A,R,G)},_Cy:function(E,f,C,l){var t=f_core,u="f_columnSortDialog_radio_text",v="radio",d="input",h="20px",g="middle",c="f_columnSortDialog_radio",s="td",o="label",p="tr",a=f_resourceBundle.Get(f_columnSortDialog),b=t.B(E,"table",{cellPadding:0,cellSpacing:2}),m=t.B(b,"tbody"),n=t.B(m,p),r,e,i
n.verticalAlign=g
n.style.height=h
r=t.B(n,s)
e=t.B(r,o,{className:u})
i=t.B(e,d,{type:v,name:f,id:f+"_asc",value:"ascendant",className:c})
l.push(i)
e.appendChild(e.ownerDocument.createTextNode(a.f_get("ASCENDANT")))
n=t.B(m,p)
n.verticalAlign=g
n.style.height=h
r=t.B(n,s)
e=t.B(r,o,{className:u})
i=t.B(e,d,{type:v,name:f,id:f+"_desc",value:"descendant",className:c})
l.push(i)
e.appendChild(e.ownerDocument.createTextNode(a.f_get("DESCENDANT")))
return b},s_:function(){var n,e=this,t
if(t=e._ss){e._ss=n
f_classLoader.Destroy(t)}e.f_super(arguments)},_ty:function(){var e=this,t=e.f_super(arguments)
return t+"\n[f_columnSortDialog title='"+e._L+"' text='"+e._l+"' defaultValue='"+e._0a+"']"}},statics:{w:{width:250,height:272,dialogPriority:0,styleClass:"f_columnSortDialog",backgroundMode:"light"},APPLY_BUTTON_STYLE:1<<20,Initializer:function(){f_grid.RegisterSortManager("dialog",function(e){var t=e.f_getComponent(),n=f_columnSortDialog.f_newInstance(t)
n.f_open()})}}});